name: Deploy ipynb.js.org
on:
  push:
    branches:
      - master
      - viewer  # TODO: remove
jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up and restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build ipynb-viewer
        run: BUILD_DESTDIR=$(pwd)/site yarn workspace ipynb2html-viewer build-site

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true
